### ISSUE TITLE
🦋 Manage a 404 behavior (& other errors)

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#890]
Add a behavior selector in /admin/config (similar to what was done in lightning administration for invoice info selector)

Choices :
- display error (current behavior)
- display CMS page /error
- redirect to page /[to-define] + custom error message in a page headband

For the last :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/c0c3616d-a213-4981-8fc1-c2e7dd24f4fd)

You can take inspiration for redirection from error  from this commit : https://github.com/B2Bitcoin/beBOP/commit/1becd1091790056e1baae087f28a50441b6888d3

In the future it would be good to be able to define a global behavior on errors, but also to have a specific behavior on a specific error code, so keep that in mind while implementing this ticket to make the later full implementation easier.

**Comment by coyotte508** [comment]
I think we should never redirect to another page in case of error.

Instead find a way to display the contents of the CMS error page on the current page if we want.

With a way to display the error message & error code if we want with a template.

Current way (redirecting to /error) is because it was tricky to do otherwise, but if we want to go further we should do it righit
